//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apolices
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public int FIPEId { get; set; }
        public int AnoFabricacao { get; set; }
        public int Combustivel { get; set; }
        public string Chassi { get; set; }
        public string Placa { get; set; }
        public bool Roubo { get; set; }
        public bool Vidros { get; set; }
        public bool Acidentes { get; set; }
        public bool DanosTerceiros { get; set; }
        public bool FranquiaRed { get; set; }
        public double ValorDoBem { get; set; }
        public double ValorFranquia { get; set; }
        public double ValorApolice { get; set; }
        public double ValorPremio { get; set; }
    
        public virtual FIPE FIPE { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Clientes Clientes1 { get; set; }
    }
}
