//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIPE()
        {
            this.Apolices = new HashSet<Apolices>();
        }
    
        public int Id { get; set; }
        public int ModeloId { get; set; }
        public int Ano { get; set; }
        public double Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apolices> Apolices { get; set; }
        public virtual Modelos Modelos { get; set; }
    }
}
